name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker CI/CD Pipeline"]
    types:
        - completed

jobs:
  build:
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Pull Docker Image
      run: docker pull kshitijsingh1076222/cicd-pipeline:latest
    - name: Delete Old Docker Image
      run: docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: docker run -d -p 8080:3000 --name cicd-pipeline-container kshitijsingh1076222/cicd-pipeline:latest
